[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_program = "9XBuf3c7x5qjXNwJhZYstqGesdXVD68Jqv6QDj8CVXax"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\kapil\.config/solana/id.json'

[scripts]
test = "yarn run mocha -t 1000000 tests/"
